# Generated by Django 3.2.8 on 2021-10-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aliens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('especie', models.CharField(max_length=20)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=2)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=2)),
                ('forca', models.CharField(choices=[('0%', '0%'), ('25%', '25%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], max_length=20)),
                ('inteligencia', models.CharField(choices=[('0%', '0%'), ('25%', '25%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], max_length=20)),
                ('agilidade', models.CharField(choices=[('0%', '0%'), ('25%', '25%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], max_length=20)),
            ],
        ),
    ]
