# Generated by Django 3.2.8 on 2021-10-28 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aliens', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aliens',
            new_name='Alien',
        ),
    ]
