# Generated by Django 3.2.8 on 2021-10-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliens', '0003_alien_planetan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alien',
            name='altura',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='alien',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
