# Generated by Django 3.2.5 on 2021-10-29 12:34

import aliens.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliens', '0004_auto_20211028_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='alien',
            name='imagem',
            field=models.ImageField(blank=True, upload_to=aliens.models.up_img_alien),
        ),
    ]
